In [45]:
import numpy as np

myArr = np.array([1,2,3,4,5,6,7,8,9,10])
'''
[1,2,3,4,5]
[6,7,8,9,10]
'''
myArr2 = myArr.reshape((2,5))

print(myArr2[1,0:3])
print(myArr2[0,:3])
print(myArr2[:,0])

[6 7 8]
[1 2 3]
[1 6]


In [48]:
print(myArr2.sum(axis=0))
print(myArr2.sum(axis=1))

[ 7  9 11 13 15]
[15 40]


mask & subsetting

In [60]:
president = np.array([45, 67, 53, 50, 30, 34, 39, 40])
mask = president[0:] <= 45

youngPresident = president[mask, ]
print(youngPresident)

[45 30 34 39 40]
